version: '3.3'

services:
  database:
    container_name: 'Projecto_PAW_database'
    restart: always
    image: postgres:12
    volumes:
      - database-data:/var/lib/paw01project/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_DB=apidb
    ports:
      - "5432:5432"
    networks: 
      - backend_network

  backend:
    container_name: 'Projecto_PAW_backend'
    restart: unless-stopped
    build:
      context: './backend'
      dockerfile: 'Dockerfile'
    volumes:
        - ./backend:/go/src/projetoapi
    depends_on:
        - database
    environment: 
        - WAIT_HOSTS=database:5432
        - CHOKIDAR_USEPOLLING=true
    networks:
        - backend_network
        - frontend_network
    links:
        - database
      
  frontend:
    container_name: 'Projecto_PAW_frontend'
    restart: unless-stopped
    depends_on:
        - backend
        - sockets
    build:
        context: './frontend'
        dockerfile: 'Dockerfile'
    volumes:
        - ./frontend:/app
        - /app/node_modules
    environment: 
        - CHOKIDAR_USEPOLLING=true
    networks:
        - frontend_network

  sockets:
    container_name: 'Projecto_PAW_sockets'
    restart: unless-stopped
    depends_on:
      - database
    build: 
      context: './sockets'
      dockerfile: 'Dockerfile'
    volumes:
      - ./sockets:/app
      - /app/node_modules
    networks: 
      - frontend_network
    links: 
       - database

  proxy:
    container_name: 'Projecto_PAW_proxy'
    restart: always
    depends_on: 
      - frontend
      - backend
    build:
      context: './proxy'
      dockerfile: 'Dockerfile'
    ports:
      - '5000:80'
    networks: 
      - frontend_network

  

volumes:
  database-data:

networks:
    backend_network:
        driver: bridge
    frontend_network:
        driver: bridge