version: "3.8"
services:
    db:
        image: postgres:13.0
        container_name: 'POSTGRES'
        restart: unless-stopped
        environment: 
            DATABASE: 'db'
            ROOT_PASSWORD: '12345678'
        ports:
         - '3306:3306'
        expose:
         - '3306'
        volumes:
         - db-data:/var/lib/postgres
        networks:
         - paw-network

    web:
        container_name: 'Projecto PAW'
        restart: unless-stopped
        depends_on: 
         - db
        build:
            context: '.'
            dockerfile: 'Dockerfile'
        ports:
         - "8080:8080"
        networks: 
         - paw-network

volumes:
    db-data:

networks:
    paw-network:
        driver: bridge
