version: "3.3"
services:
    projecto:
        container_name: 'Projecto_PAW'
        restart: unless-stopped
        build:
            context: '.'
            dockerfile: 'Dockerfile'
        volumes:
            - './:/usr/src/app'
            - /usr/src/app/node_modules
        ports:
            - '8080:8080'