definitions:
  model.Claims:
    properties:
      admin:
        type: boolean
      id:
        type: integer
      name:
        type: string
      username:
        type: string
    type: object
  model.Worker:
    properties:
      admin:
        type: boolean
      name:
        type: string
      password:
        type: string
      username:
        type: string
      zones:
        items:
          $ref: '#/definitions/model.Zone'
        type: array
    type: object
  model.Zone:
    properties:
      latitude:
        type: number
      limits:
        type: integer
      longitude:
        type: number
      name:
        type: string
      pplCount:
        type: integer
      workers:
        items:
          $ref: '#/definitions/model.Worker'
        type: array
    type: object
info:
  contact: {}
paths:
  /api/admin/associate:
    delete:
      consumes:
      - application/json
      description: Desassocia workers a zonas vis IDs
      parameters:
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Worker'
            type: array
        "404":
          description: Not found
      security:
      - BearerAuth: []
      summary: Desassocia workers a zonas
    post:
      consumes:
      - application/json
      description: Associa workers a zonas via IDs
      parameters:
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Not Found
        "404":
          description: Not Found
      security:
      - BearerAuth: []
      summary: Associa workers a zonas
  /api/admin/users:
    delete:
      consumes:
      - application/json
      description: Exclui uma zona realizada
      operationId: get-string-by-int
      parameters:
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Worker ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Worker'
        "404":
          description: Not found
      security:
      - BearerAuth: []
      summary: Exclui uma worker pelo ID
    get:
      consumes:
      - application/json
      description: Exibe a lista, sem todos os campos, de todas as zonas
      parameters:
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Worker'
            type: array
        "404":
          description: Not found
      security:
      - BearerAuth: []
      summary: Recupera os users
    post:
      consumes:
      - application/json
      description: Adiciona um worker na base de dados
      parameters:
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Add worker
        in: body
        name: worker
        required: true
        schema:
          $ref: '#/definitions/model.Worker'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Worker'
        "400":
          description: Bad request
        "404":
          description: Not found
      security:
      - BearerAuth: []
      summary: Adiciona um Worker
  /api/admin/zones:
    post:
      consumes:
      - application/json
      description: Adiciona uma zona
      parameters:
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Add zone
        in: body
        name: zone
        required: true
        schema:
          $ref: '#/definitions/model.Zone'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Zone'
        "400":
          description: Bad request
        "404":
          description: Not found
      security:
      - BearerAuth: []
      summary: Adicionar uma zona
  /api/admin/zones/{id}:
    delete:
      consumes:
      - application/json
      description: Exclui uma zona realizada
      operationId: get-string-by-int
      parameters:
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Zone ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Zone'
        "404":
          description: Not found
      security:
      - BearerAuth: []
      summary: Exclui uma zona pelo ID
  /api/login:
    post:
      consumes:
      - application/json
      description: Autentica o utilizador e gera o token para os próximos acessos
      parameters:
      - description: Do login
        in: body
        name: json
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Claims'
        "400":
          description: Bad request
        "401":
          description: Unauthorized
      summary: Realizar autenticação
  /api/refresh_token:
    put:
      consumes:
      - application/json
      description: Atualiza o token de autenticação do usuário
      parameters:
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Claims'
        "400":
          description: Bad request
        "401":
          description: Unauthorized
      security:
      - BearerAuth: []
      summary: Atualiza token de autenticação
  /api/zones/all:
    get:
      consumes:
      - application/json
      description: Exibe a lista de todas as zonas
      parameters:
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Zone'
            type: array
        "404":
          description: Not found
      security:
      - BearerAuth: []
      summary: Recupera as zonas
  /api/zones/id/{id}:
    get:
      consumes:
      - application/json
      description: Exibe a lista de todas as zonas
      parameters:
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Zone ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Zone'
        "404":
          description: Not found
      security:
      - BearerAuth: []
      summary: Recupera uma zona
  /api/zones/id/{id}/add:
    post:
      consumes:
      - application/json
      description: Adiciona um worker à zona
      parameters:
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Add worker
        in: body
        name: worker
        required: true
        schema:
          $ref: '#/definitions/model.Worker'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Worker'
        "400":
          description: Bad request
        "404":
          description: Not found
      security:
      - BearerAuth: []
      summary: Adicionar um worker
  /api/zones/id/{id}/remove:
    post:
      consumes:
      - application/json
      description: Remove um worker da zona
      parameters:
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Worker ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Worker'
        "400":
          description: Bad request
        "404":
          description: Not found
      security:
      - BearerAuth: []
      summary: Remove um worker
  /api/zones/worker:
    get:
      consumes:
      - application/json
      description: Exibe a lista de todas as zonas de um worker
      parameters:
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Zone'
            type: array
        "404":
          description: Not found
      security:
      - BearerAuth: []
      summary: Recupera as zonas de um worker
swagger: "2.0"
